# Generated by Django 5.1.7 on 2025-03-11 19:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_contactmessage_petcaretip_clinic_phone_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="profile_picture",
        ),
    ]
