# Generated by Django 5.1.6 on 2025-03-13 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contactus_contactmessage_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
