# Generated by Django 5.1.6 on 2025-03-13 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinicreview',
            old_name='text',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='veterinarianreview',
            old_name='created_at',
            new_name='date_submitted',
        ),
    ]
