# Generated by Django 5.1.6 on 2025-03-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_text_clinicreview_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='veterinarians',
            field=models.ManyToManyField(related_name='clinics', to='core.veterinarian'),
        ),
    ]
