# Generated by Django 5.1.6 on 2025-03-19 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_clinic_veterinarians'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='veterinarians',
        ),
        migrations.RemoveField(
            model_name='veterinarianreview',
            name='veterinarian',
        ),
        migrations.RemoveField(
            model_name='veterinarianreview',
            name='user',
        ),
        migrations.DeleteModel(
            name='Veterinarian',
        ),
        migrations.DeleteModel(
            name='VeterinarianReview',
        ),
    ]
