# Generated by Django 5.1.6 on 2025-03-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_clinic_veterinarians_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='location_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
