# Generated by Django 5.1.6 on 2025-03-19 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_clinic_location_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinic',
            old_name='location_url',
            new_name='website2',
        ),
    ]
