# Generated by Django 5.1.6 on 2025-03-19 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_location_url_clinic_website2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinic',
            old_name='website2',
            new_name='location',
        ),
    ]
