from django.db import models
from django.contrib.auth.models import User  # Import User model for Profile model

# Clinic model to represent a veterinary clinic
class Clinic(models.Model):
    name = models.CharField(max_length=200)  
    description = models.TextField()  
    contact_info = models.CharField(max_length=200) 
    address = models.TextField()  
    phone_number = models.CharField(max_length=20)  
    website = models.URLField(blank=True, null=True) 
    location = models.URLField(null=True, blank=True)  
    image = models.ImageField(upload_to='clinic_images/', null=True, blank=True) 
    

    def __str__(self):
        return self.name


# FAQ model to represent frequently asked questions
class FAQ(models.Model):
    question = models.CharField(max_length=255)  # FAQ question
    answer = models.TextField()  # FAQ answer

    def __str__(self):
        return self.question


# Review model to represent reviews for clinics
class Review(models.Model):
    clinic = models.ForeignKey(Clinic, on_delete=models.CASCADE, related_name='reviews') 
    user = models.ForeignKey(User, on_delete=models.CASCADE) 
    rating = models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])  # Rating (1-5)
    review_text = models.TextField()  
    date_submitted = models.DateTimeField(auto_now_add=True)  

    def __str__(self):
        return f'Review by {self.user.username} for {self.clinic.name}'


# ContactMessage model to represent messages sent through the contact form
class ContactMessage(models.Model):
    name = models.CharField(max_length=255) 
    email = models.EmailField()  
    subject = models.CharField(max_length=255)  
    message = models.TextField()  
    sent_at = models.DateTimeField(auto_now_add=True)  

    def __str__(self):
        return f"Message from {self.name} on {self.sent_at}"


# Report model to represent a report generated by the admin or staff
class Report(models.Model):
    report_type = models.CharField(max_length=255)  # Type of the report (Contact Messages)
    content = models.TextField()  # Content of the report
    generated_by = models.ForeignKey(User, on_delete=models.CASCADE)  # Admin who generated the report
    generated_at = models.DateTimeField(auto_now_add=True)  

    def __str__(self):
        return f"{self.report_type} - {self.generated_by.username}"
    

class ContactUs(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


# ContactUsMessage model to store messages with an optional authenticated user
class ContactUsMessage(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)  
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    sent_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Message from {self.name} - {self.subject}"
    

# PetCareTip model to represent pet care tips, managed only by the admin
class PetCareTip(models.Model):
    title = models.CharField(max_length=200)  
    content = models.TextField()  
    created_at = models.DateTimeField(auto_now_add=True)  
    updated_at = models.DateTimeField(auto_now=True)  

    def __str__(self):
        return self.title



# ClinicReview model to represent reviews for clinics
class ClinicReview(models.Model):
    clinic = models.ForeignKey(Clinic, on_delete=models.CASCADE)  
    user = models.ForeignKey(User, on_delete=models.CASCADE) 
    rating = models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])
    comment = models.TextField()  
    date_submitted = models.DateTimeField(auto_now_add=True)  

    def __str__(self):
        return f'Review by {self.user.username} for {self.clinic.name}'
    


class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="messages")
    subject = models.CharField(max_length=255)
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.subject